#
#  Author: Hari Sekhon
#  Date: 2024-10-09 06:32:44 +0300 (Wed, 09 Oct 2024)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/GitHub-Actions
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#                         S y s t e m d   A n a l y z e
# ============================================================================ #

---
name: Systemd-Analyze Verify

on:
  workflow_call:
    inputs:
      debug:
        type: string
        required: false
        default: false
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  #schedule:
  #  - cron: '0 0 * * 1'

permissions:
  contents: read

defaults:
  run:
    shell: bash -euxo pipefail {0}

env:
  DEBUG: ${{ inputs.debug == true || github.event.inputs.debug == 'true' || '' }}

jobs:
  systemd_analyze_verify:
    name: Systemd-Analyze Verify
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Environment
        run: env | sort

      - name: Install Git
        run: dnf install -y git

      - name: Install Systemd
        run: dnf install -y systemd

      - name: Git version
        run: git --version

      - uses: actions/checkout@v3
        with:
          submodules: recursive  # requires Git 2.18+ to be installed first

        # to avoid this error:
        #
        #   Command /usr/local/bin/prometheus is not executable: No such file or directory
        #
      - name: Replace ExecStart binaries in Systemd unit files with /bin/true to avoid executable not found errors
        run: |
          find . -name '*.service' -type f |
          xargs sed -i 's|ExecStart=.*|ExecStart=/bin/true|'

      - name: Systemd Analyze
        run: |
          find . -name '*.service' -type f |
          xargs -I {} sh -c 'systemd-analyze verify {} || exit 1'
